// <auto-generated />
using System;
using Api.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.EF.Migrations
{
    [DbContext(typeof(ApiDbContextStubbed))]
    partial class ApiDbContextStubbedModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Api.Entities.Dice", b =>
                {
                    b.Property<int>("NbFaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("NbFaces");

                    b.ToTable("dices");

                    b.HasData(
                        new
                        {
                            NbFaces = 2
                        },
                        new
                        {
                            NbFaces = 3
                        },
                        new
                        {
                            NbFaces = 4
                        },
                        new
                        {
                            NbFaces = 5
                        },
                        new
                        {
                            NbFaces = 6
                        });
                });

            modelBuilder.Entity("Api.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("profiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5dab26f-6975-483c-8bb6-1cd9b19190a0"),
                            Name = "Perret",
                            Surname = "Louis"
                        },
                        new
                        {
                            Id = new Guid("98b76d55-e413-4ad0-97ab-bed373a13a65"),
                            Name = "Grienenberger",
                            Surname = "Côme"
                        },
                        new
                        {
                            Id = new Guid("bd68c485-c883-44c5-a235-9190d3049d4a"),
                            Name = "Malvezin",
                            Surname = "Neitah"
                        });
                });

            modelBuilder.Entity("Api.Entities.Throw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("throws");

                    b.HasData(
                        new
                        {
                            Id = new Guid("825e122e-897f-4a59-93be-c8c554a86b53"),
                            DiceId = 2,
                            Result = 1
                        },
                        new
                        {
                            Id = new Guid("003a02ce-db1e-405b-88a9-a6807f591c14"),
                            DiceId = 2,
                            Result = 2
                        },
                        new
                        {
                            Id = new Guid("0a8e177e-fbd2-4ba5-80d3-506f22709592"),
                            DiceId = 4,
                            Result = 4
                        },
                        new
                        {
                            Id = new Guid("ed12df19-cf27-4e14-9f7c-bb3d2774a52d"),
                            DiceId = 4,
                            Result = 3
                        },
                        new
                        {
                            Id = new Guid("0a7aa0d4-efac-467e-b151-e6dc17facbd0"),
                            DiceId = 3,
                            Result = 3
                        },
                        new
                        {
                            Id = new Guid("1c786418-3d11-4947-8901-53b35ac76502"),
                            DiceId = 6,
                            Result = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
